/*
 * Posts service
 *
 * Posts service
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Blogpost.WebApi.Models;

/// <summary>
///
/// </summary>
[DataContract]
public partial class CommentBase
{
    /// <summary>
    /// Идентификатор комментария
    /// </summary>
    /// <value>Идентификатор комментария</value>
    [DataMember(Name = "id")]
    public Guid? Id { get; set; }

    /// <summary>
    /// Содержание комментария
    /// </summary>
    /// <value>Содержание комментария</value>
    [DataMember(Name = "content")]
    public string Content { get; set; }

    /// <summary>
    /// Количество лайков
    /// </summary>
    /// <value>Количество лайков</value>
    [DataMember(Name = "likes")]
    public int? Likes { get; set; }

    /// <summary>
    /// Gets or Sets CreatedBy
    /// </summary>
    [DataMember(Name = "createdBy")]
    public CreatedBy CreatedBy { get; set; }

    /// <summary>
    /// Дата создания поста
    /// </summary>
    /// <value>Дата создания поста</value>
    [DataMember(Name = "createdAt")]
    public DateTime? CreatedAt { get; set; }

    /// <summary>
    /// Текущий пользователь добавил лайк комментарию
    /// </summary>
    /// <value>Текущий пользователь добавил лайк комментарию</value>
    [DataMember(Name = "hasLikeFromCurrentUser")]
    public bool HasLikeFromCurrentUser { get; set; }
}