/*
 * Profiles service
 *
 * Profiles service
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Runtime.Serialization;

namespace Blogpost.WebApi.Models
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public partial class Subscriber
    {
        /// <summary>
        /// Идентификатор профиля
        /// </summary>
        /// <value>Идентификатор профиля</value>
        [DataMember(Name = "id")]
        public Guid? Id { get; set; }

        /// <summary>
        /// Имя пользователя
        /// </summary>
        /// <value>Имя пользователя</value>
        [DataMember(Name = "name")]
        public string Name { get; set; }
    }
}
